name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    name: Build & Release
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore Dependencies
        run: dotnet restore ./PreFusion_Firmware_Tools/PreFusionFirmwareTools.sln

      - name: Build (Release)
        run: dotnet build ./PreFusion_Firmware_Tools/PreFusionFirmwareTools.sln --configuration Release --no-restore

      - name: Publish WinForms App
        run: |
          dotnet publish ./PreFusion_Firmware_Tools/PreFusion.WinForms/PreFusion.WinForms.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o ./publish

      - name: Create Zip Archive
        run: |
          Compress-Archive -Path ./publish/* -DestinationPath ./PreFusion_Firmware_Tools_win-x64.zip

      - name: Setup Inno Setup
        run: |
          choco install innosetup --no-progress

      - name: Compile Installer
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" ./Installer/setup.iss

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PreFusion_Build_Package
          path: |
            ./PreFusion_Firmware_Tools_win-x64.zip
            ./Output/PreFusion_Setup_win-x64.exe

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./PreFusion_Firmware_Tools_win-x64.zip
            ./Output/PreFusion_Setup_win-x64.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
